# Generated by Django 5.2.5 on 2025-10-02 12:02

from django.db import migrations


def seed_educational_content(apps, schema_editor):
    EducationalContent = apps.get_model("home", "EducationalContent")

    contents = [
        {
            "title": "Start Your Savings Journey Today",
            "content": "Every shilling you save brings you closer to your dreams. Start small—even 1,000 UGX daily grows to 365,000 UGX yearly. The best time to start saving is now.",
            "language": "English",
        },
        {
            "title": "Set Clear Savings Goals",
            "content": "Define what you're saving for: school fees, emergency fund, business capital, or a new home. Write down your goal amount and deadline. This makes saving purposeful and motivating.",
            "language": "English",
        },
        {
            "title": "The 50-30-20 Savings Rule",
            "content": "Try allocating your income wisely: 50% for needs (food, rent), 30% for wants (entertainment), and 20% for savings. Adjust these percentages to fit your situation, but always prioritize saving something.",
            "language": "English",
        },
        {
            "title": "Build an Emergency Fund First",
            "content": "Save at least 3–6 months of living expenses for emergencies like medical bills or job loss. Keep this money separate and only use it for true emergencies. This protects your other savings goals.",
            "language": "English",
        },
        {
            "title": "Automate Your Savings",
            "content": "Set up automatic transfers to your savings account right after receiving income. When you save first before spending, you're more likely to reach your goals. Make savings a non-negotiable habit.",
            "language": "English",
        },
        {
            "title": "Beware of Get-Rich-Quick Schemes",
            "content": "Fraudsters promise unrealistic returns like doubling your money in weeks. Legitimate investments take time. Never invest your savings in schemes that pressure you to act fast or recruit others.",
            "language": "English",
        },
        {
            "title": "Protect Your Savings from Fraud",
            "content": "Never share your mobile money PIN or bank passwords. Fraudsters may claim to verify your account or offer investment opportunities. Always confirm through official channels before moving your savings.",
            "language": "English",
        },
        {
            "title": "Recognize Fake Investment Apps",
            "content": "Scammers create fake apps promising high returns. Only use licensed financial institutions. Verify company registration with Uganda's Financial Intelligence Authority before investing your hard-earned savings.",
            "language": "English",
        },
        {
            "title": "Avoid Impulsive Spending",
            "content": "Before making non-essential purchases, wait 24 hours. Ask yourself: Do I need this, or do I want it? This simple pause helps you save more and spend wisely on what truly matters.",
            "language": "English",
        },
        {
            "title": "Diversify Your Savings",
            "content": "Don't keep all savings in one place. Use a mix: mobile money for easy access, bank savings accounts for security, and SACCOs or investment groups for growth. This reduces risk and maximizes returns.",
            "language": "English",
        },
        {
            "title": "Track Your Spending Habits",
            "content": "Write down or use apps to monitor where your money goes monthly. Identifying unnecessary expenses helps you redirect that money into savings. Small leaks can sink big ships.",
            "language": "English",
        },
        {
            "title": "Beware of Fake Prize Notifications",
            "content": "Messages claiming you won money or prizes are usually scams designed to steal your savings. Never send fees to claim winnings or share personal banking details with unknown contacts.",
            "language": "English",
        },
        {
            "title": "Save Before You Borrow",
            "content": "Loans cost money through interest. Build savings first to reduce borrowing needs. If you must borrow, ensure you can repay comfortably while still continuing to save for your future.",
            "language": "English",
        },
        {
            "title": "Recognize Pyramid Schemes",
            "content": "Schemes that require recruiting others to earn returns will eventually collapse. Your savings are at risk. Legitimate savings groups don't depend on endless recruitment. Always verify before joining any group.",
            "language": "English",
        },
        {
            "title": "Plan for Long-Term Goals",
            "content": "Retirement, children's education, or land purchase require years of consistent saving. Start early to benefit from compound growth. Even small monthly contributions grow significantly over time.",
            "language": "English",
        },
        {
            "title": "Review and Adjust Your Savings Plan",
            "content": "Check your savings progress monthly. Celebrate milestones reached. If income increases, increase your savings rate too. Life changes, and your savings strategy should adapt accordingly.",
            "language": "English",
        },
        {
            "title": "Avoid Emotional Spending",
            "content": "Don't spend savings when stressed, happy, or pressured by friends. Emotional purchases rarely bring lasting satisfaction. Stick to your savings goals and spend only on planned necessities.",
            "language": "English",
        },
        {
            "title": "Verify Before You Transfer",
            "content": "Fraudsters impersonate family or friends requesting urgent money. Always call to verify requests before sending your savings. A few minutes of confirmation can save you from losing everything.",
            "language": "English",
        },
        {
            "title": "Join Legitimate Savings Groups",
            "content": "SACCOs and Village Savings Groups help build discipline and access to loans. Ensure the group is registered, has clear rules, and keeps proper records. Your savings deserve protection and transparency.",
            "language": "English",
        },
        {
            "title": "Teach Your Children to Save",
            "content": "Help children develop savings habits early. Give them a savings box, set goals together, and celebrate when goals are reached. Financial literacy starts at home and builds generational wealth.",
            "language": "English",
        },
    ]

    for item in contents:
        EducationalContent.objects.create(**item)


def unseed_educational_content(apps, schema_editor):
    EducationalContent = apps.get_model("home", "EducationalContent")
    EducationalContent.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_userprofile_email_and_more"),  # Update if your last migration differs
    ]

    operations = [
        migrations.RunPython(seed_educational_content, unseed_educational_content),
    ]
