# Generated by Django 5.2.5 on 2025-10-03 19:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_seed_educational_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedmessage',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
