# Generated by Django 5.2.5 on 2025-10-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_scannedmessage_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannedmessage',
            name='related_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
