# Generated by Django 5.2.5 on 2025-10-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_scannedmessage_related_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedmessage',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
