# Generated by Django 5.2.5 on 2025-10-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_transaction_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentoption',
            name='category',
            field=models.CharField(choices=[('Investment', 'Investment'), ('Insurance', 'Insurance'), ('Real Estate', 'Real Estate'), ('Vehicle Financing', 'Vehicle Financing'), ('Shares', 'Shares')], default='Investment', max_length=50),
        ),
    ]
