# Generated by Django 5.2.5 on 2025-10-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_investmentoption_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentoption',
            name='category',
            field=models.CharField(blank=True, choices=[('Investment', 'Investment'), ('Insurance', 'Insurance'), ('Real Estate', 'Real Estate'), ('Vehicle Financing', 'Vehicle Financing'), ('Shares', 'Shares')], default='Investment', max_length=50, null=True),
        ),
    ]
