# Generated by Django 6.0.3 on 2026-04-22 17:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_investmentoption_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_number',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savinggoal',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pin_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pin_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pin_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='transaction_pin_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(default='SilentGuard Bank', max_length=100),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investmentoption',
            name='category',
            field=models.CharField(choices=[('Investment', 'Investment'), ('Insurance', 'Insurance'), ('Real Estate', 'Real Estate'), ('Vehicle Financing', 'Vehicle Financing'), ('Shares', 'Shares')], default='Investment', max_length=50),
        ),
        migrations.AlterField(
            model_name='investmentoption',
            name='return_rate',
            field=models.DecimalField(decimal_places=2, help_text='Expected return % per year', max_digits=5),
        ),
        migrations.AlterField(
            model_name='savinggoal',
            name='current_savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='savinggoal',
            name='duration',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], default='Yearly', max_length=20),
        ),
        migrations.AlterField(
            model_name='savinggoal',
            name='goal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='scannedmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('Transfer', 'Transfer to Savings'), ('Purchase', 'Purchase'), ('Bill Payment', 'Bill Payment'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Ugandan phone number (07XXXXXXXX)', regex='^07\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('agent', 'Mobile Money Agent'), ('student', 'Student'), ('vendor', 'Vendor'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
