# Generated by Django 6.0.3 on 2026-05-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_bankaccount_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalcontent',
            name='category',
            field=models.CharField(choices=[('Savings', 'Savings'), ('Fraud Prevention', 'Fraud Prevention'), ('Financial Planning', 'Financial Planning')], default='Savings', max_length=50),
        ),
        migrations.AddField(
            model_name='educationalcontent',
            name='icon',
            field=models.CharField(choices=[('fa-piggy-bank', 'Piggy Bank'), ('fa-bullseye', 'Bullseye'), ('fa-chart-pie', 'Chart Pie'), ('fa-first-aid', 'First Aid'), ('fa-exclamation-triangle', 'Warning'), ('fa-shield-alt', 'Shield'), ('fa-shopping-cart', 'Shopping Cart'), ('fa-layer-group', 'Layers'), ('fa-user-slash', 'User Slash'), ('fa-mobile-alt', 'Mobile'), ('fa-lock', 'Lock'), ('fa-chart-line', 'Chart Line')], default='fa-piggy-bank', max_length=50),
        ),
        migrations.AddField(
            model_name='educationalcontent',
            name='summary',
            field=models.TextField(default='', help_text='Short preview shown on the card (2-3 sentences)'),
        ),
        migrations.AlterField(
            model_name='educationalcontent',
            name='content',
            field=models.TextField(help_text='Full article content shown when user clicks Learn More'),
        ),
    ]
